variables:
        OS_PODS: "mq1 keystone glance cinder neutron client"
        CLOUDDEV: "$CI_PROJECT_DIR"
        CLOUDDEV_KUB: "/tmp/kubernetes"
        CLOUDDEV_PUPPET: "$CI_PROJECT_DIR/ws/cern-puppet"

before_script:
        - echo $SVCBUILD_PASSWORD | kinit svcbuild@CERN.CH

rebuild:
        only:
                - master
        script:
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh centos
                - ./cci-dev.sh prepare
                - ./cci-dev.sh restart
                - ./cci-dev.sh launch
        tags:
                - cci-builder
update:
        except:
                - master
        script:
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh centos
                - ./cci-dev.sh prepare
                - ./cci-dev.sh restart
                - ./cci-dev.sh launch
        tags:
                - cci-builder
