variables:
        OS_PODS: "keystone glance cinder"
        CLOUDDEV: "$CI_PROJECT_DIR"
        CLOUDDEV_KUB: "/tmp/kubernetes"
        CLOUDDEV_PUPPET: "$CI_PROJECT_DIR/ws/cern-puppet"


rebuild:
        only:
                - master
        script:
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh centos
                - ./cci-dev.sh prepare
                - ./cci-dev.sh restart
                - ./cci-dev.sh launch
        tags:
                - cci-builder
update:
        except:
                - master
        script:
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh centos
                - ./cci-dev.sh prepare
                - ./cci-dev.sh restart
                - ./cci-dev.sh launch
        tags:
                - cci-builder
