variables:
        OS_PODS: "keystone glance cinder"
        CLOUDDEV: "$CI_PROJECT_DIR/ws/cloud-dev"
        CLOUDDEV_KUB: "$CI_PROJECT_DIR/ws/kubernetes"
        CLOUDDEV_PUPPET: "$CI_PROJECT_DIR/ws/cern-puppet"
        USER: "root"

rebuild:
        only:
                - master
        script:
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh centos
                - sudo -E ./cci-dev.sh prepare
                - sudo -E ./cci-dev.sh restart
                - sudo -E ./cci-dev.sh launch
        tags:
                - cci-builder
update:
        except:
                - master
        script:
                - sudo -p /kubernetes
                - cd $CLOUDDEV/scripts
                - sudo -E ./cci-dev.sh restart
                - sudo -E ./cci-dev.sh launch
        tags:
                - cci-builder
