FROM docker.cern.ch/cloud-infrastructure/ciadm
MAINTAINER Ricardo Rocha <ricardo.rocha@cern.ch>

RUN yum clean all

RUN yum install -y \
	git \
	libyaml-devel \
	python-pip

RUN mkdir /heat-translator-build

RUN cd /heat-translator-build && \
	git clone https://github.com/MatMaul/tosca-types.git -b test && \
	git clone https://github.com/MatMaul/heat-translator.git -b test && \
	git clone https://github.com/openstack/tosca-parser.git && \
	cd tosca-parser && \
	pip install pytz && \
	pip install -r requirements.txt && \
	python setup.py install && \
	cd ../heat-translator && \
	pip install -r requirements.txt && \
	pip install requests && \
	python setup.py install

RUN cp /heat-translator-build/heat-translator/heat_translator_logging.conf /heat-translator-build/tosca-types/examples && \
	sed -i 's/SysLogHandler,//' /heat-translator-build/tosca-types/examples/heat_translator_logging.conf
