CLASSPATH='/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/axis.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/commons-discovery-0.2.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/commons-logging-1.0.4.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/jaxrpc.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/log4j-1.2.8.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/saaj.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/lib/wsdl4j-1.5.1.jar:/home/ricardo/ws/cloud-dev/landb/axis/webapps/axis/WEB-INF/classes'

default:
	javac -classpath $(CLASSPATH) axis/webapps/axis/WEB-INF/classes/NetworkDataTypes/*java
	javac -classpath $(CLASSPATH) axis/webapps/axis/WEB-INF/classes/NetworkService/*java
