apiVersion: v1beta3
kind: Pod
metadata:
  name: cinder
  labels:
    name: cinder
spec:
  containers:
    - name: cinder
      image: docker.cern.ch/cloud-infrastructure/puppetagent
      privileged: true
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
      command:
        - /usr/sbin/init
      ports:
        - containerPort: 8776
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
