apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: cirros
  labels:
    name: cirros
spec:
  replicas: 1
  selector:
    name: cirros
  template:
    metadata:
      name: cirros
      labels:
        name: cirros
    spec:
      containers:
        - name: cirros
          image: cirros
