apiVersion: v1beta3
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
    - name: client
      image: docker-reg.cern.ch:5000/puppetagent:latest
      privileged: true
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
        - name: tempestcfg
          mountPath: /etc/tempest
      command:
        - /usr/sbin/init
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: tempestcfg
      hostPath:
        path: /opt/cloud-dev/tempest
