apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
    - name: client
      image: docker.cern.ch/cloud-infrastructure/puppetagent
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
        - name: tempestcfg
          mountPath: /etc/tempest
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: run
          mountPath: /run
      command:
        - /usr/sbin/init
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: tempestcfg
      hostPath:
        path: /opt/cloud-dev/tempest
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: run
      emptyDir: 
