apiVersion: v1
kind: Pod
metadata:
  name: compute
  labels:
    name: compute
spec:
  containers:
    - name: compute
      image: docker.cern.ch/cloud-infrastructure/puppetagent
      securityContext:
        privileged: true
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
        - name: yumcache
          mountPath: /var/cache/yum
      command:
        - /usr/sbin/init
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: yumcache
      hostPath:
        path: /opt/cloud-dev/cache
