apiVersion: v1beta3
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: 'MYSQL_ROOT_PASSWORD'
          value: '123456'
      ports:
        - containerPort: 3306
    - name: rabbitmq
      image: rabbitmq
    - name: ldap
      image: docker-reg.cern.ch:5000/ldap
      env:
        - name: LDAP_ROOT_PASSWORD
          value: '123456'
        - name: LDAP_MANAGER_PASSWORD
          value: '123456'
      ports:
        - containerPort: 389
      volumeMounts:
        - name: ldif
          mountPath: /ldif
  volumes:
    - name: ldif
      hostPath:
        path: /opt/ldif
