apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: controller
  name: controller
spec:
  ports:
  - name: mysql
    port: 3306
  - name: ldap
    port: 389
  - name: rabbitmq
    port: 5672
  selector:
    name: controller
