apiVersion: v1beta3
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
spec:
  containers:
    - name: keystone
      image: docker-reg.cern.ch:5000/puppetagent:latest
      privileged: true
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: factercfg
          mountPath: /etc/facter
      env:
        - name: CONTAINER
          value: keystone
      command:
        - /usr/sbin/init
      ports:
        - containerPort: 80
        - containerPort: 443
    - name: mysql
      image: mysql
      env:
        - name: 'MYSQL_ROOT_PASSWORD'
          value: '123456'
      ports:
        - containerPort: 3306
    - name: rabbitmq
      image: rabbitmq
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/puppet
    - name: factercfg
      hostPath:
        path: /opt/facter
