apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: controller
  name: controller
spec:
  ports:
  - name: keystone-plain
    port: 80
    protocol: TCP
  - name: keystone-ssl
    port: 443
    protocol: TCP
  - name: mysql
    port: 3306
  - name: ldap
    port: 389
  selector:
    name: controller
