apiVersion: v1
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
spec:
  containers:
    - name: mysql
      image: gitlab-registry.cern.ch/cloud/mysql
      env:
        - name: 'MYSQL_ROOT_PASSWORD'
          value: '123456'
      ports:
        - containerPort: 3306
    - name: ldap
      image: gitlab-registry.cern.ch/cloud/ldap
      env:
        - name: LDAP_ROOT_PASSWORD
          value: '123456'
        - name: LDAP_MANAGER_PASSWORD
          value: '123456'
      ports:
        - containerPort: 389
      volumeMounts:
        - name: ldif
          mountPath: /ldif
  volumes:
    - name: ldif
      hostPath:
        path: /opt/cloud-dev/ldap/data
