apiVersion: v1beta3
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: 'MYSQL_ROOT_PASSWORD'
          value: '123456'
      ports:
        - containerPort: 3306
    - name: rabbitmq
      image: rabbitmq
    - name: ldap
      image: docker-reg.cern.ch:5000/ldap
      env:
        - name: USE_TLS
          value: 'False'
        - name: LDAP_ORGANISATION
          value: OIS
        - name: LDAP_DOMAIN
          value: default.kubdomain.local
        - name: LDAP_ADMIN_PASSWORD
          value: '123456'
        - name: SERVER_NAME
          value: controller
      ports:
        - containerPort: 389
