apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: controller
  labels:
    name: controller
spec:
  replicas: 1
  selector:
    name: controller
  template:
    metadata:
      name: controller
      labels:
        name: controller
    spec:
      containers:
        - name: keystone
          image: rochaporto/puppetagent:latest
          privileged: true
          #capabilities:
          #  add: [SYS_ADMIN]
          volumeMounts:
            - name: puppetcfg
              mountPath: /etc/puppet
          env:
            - name: CONTAINER_TYPE
              value: keystone
          command:
            - /usr/sbin/init
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 123456
      volumes:
        - name: puppetcfg
          hostPath:
            path: /tmp/puppet
