apiVersion: v1beta3
kind: Pod
metadata:
  name: glance
  labels:
    name: glance
spec:
  containers:
    - name: glance
      image: docker-reg.cern.ch:5000/puppetagent:latest
      privileged: true
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
        - name: cephcfg
          mountPath: /etc/ceph
      env:
        - name: CONTAINER
          value: glance
      command:
        - /usr/sbin/init
      ports:
        - containerPort: 9293
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/puppet
    - name: puppetssl
      hostPath:
        path: /opt/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/facter
    - name: cephcfg
      hostPath:
        path: /opt/ceph
