apiVersion: v1
kind: Service
metadata:
  labels:
    name: keystone
  name: keystone
spec:
  ports:
  - name: keystone-plain
    port: 80
    protocol: TCP
  - name: keystone-ssl
    port: 443
    protocol: TCP
  selector:
    name: keystone
