apiVersion: v1
kind: Pod
metadata:
  name: keystone
  labels:
    name: keystone
spec:
  containers:
    - name: keystone
      image: gitlab-registry.cern.ch/cloud/puppetagent
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
#        - name: yumcache
#          mountPath: /var/cache/yum
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: run
          mountPath: /run
      command:
        - /usr/sbin/init
      ports:
        - containerPort: 80
        - containerPort: 443
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
#    - name: yumcache
#      hostPath:
#        path: /opt/cloud-dev/cache
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: run
      emptyDir: 
