apiVersion: v1
kind: Pod
metadata:
  name: landb
  labels:
    name: landb
spec:
  containers:
    - name: landb
      image: gitlab-registry.cern.ch/cloud/landb
      ports:
        - containerPort: 8443
    - name: landb-dhcp
      image: gitlab-registry.cern.ch/cloud/landb-dhcp
      ports:
        - containerPort: 67
        - containerPort: 68
  volumes:
    - name: puppet
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: puppetmodules
      hostPath:
        path: /opt/puppet-modules
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: teigifiles
      hostPath:
        path: /opt/cloud-dev/teigi/certs
    - name: teigidb
      hostPath:
        path: /opt/cloud-dev/teigi/data
