apiVersion: v1
kind: Service
metadata:
  labels:
    name: landb
  name: landb
spec:
  ports:
  - name: landb
    port: 8083
    protocol: TCP
  - name: landbssl
    port: 8443
    protocol: TCP
  - name: landb-dhcp1
    port: 67
    protocol: UDP
  - name: landb-dhcp2
    port: 68
    protocol: UDP
  selector:
    name: landb
