apiVersion: v1
kind: Pod
metadata:
  name: mq2
  labels:
    name: mq2
spec:
  containers:
    - name: mq
      image: gitlab-registry.cern.ch/cloud/puppetagent
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: puppetcfg
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: factercfg
          mountPath: /etc/facter
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: run
          mountPath: /run
      command:
        - /usr/sbin/init
      ports:
        - containerPort: 4096
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 41055
  volumes:
    - name: puppetcfg
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: run
      emptyDir: 
