apiVersion: v1
kind: Service
metadata:
  labels:
    name: mq3
  name: mq3
spec:
  ports:
  - name: erlang
    port: 4096
    protocol: TCP
  - name: epmd
    port: 4369
    protocol: TCP
  - name: mq
    port: 5672
    protocol: TCP
  - name: mqmanagement
    port: 15672
    protocol: TCP
  - name: mqcluster
    port: 41055
    protocol: TCP
  selector:
    name: mq3
