apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: puppet
  labels:
    name: puppet
spec:
  replicas: 1
  selector:
    name: puppet
  template:
    metadata:
      name: puppet
      labels:
        name: puppet
    spec:
      containers:
        - name: puppetmaster
          image: rochaporto/puppetmaster:latest
          ports:
            - containerPort: 8140
          volumeMounts:
            - name: puppet
              mountPath: /etc/puppet
            - name: puppetssl
              mountPath: /var/lib/puppet/ssl
        - name: puppetdb
          image: rochaporto/puppetdb
          ports:
            - containerPort: 8080
            - containerPort: 8081
          volumeMounts:
            - name: puppet
              mountPath: /etc/puppet
            - name: puppetssl
              mountPath: /var/lib/puppet/ssl
      volumes:
        - name: puppet
          hostPath:
            path: /tmp/puppet
        - name: puppetssl
          emptyDir: {}
