apiVersion: v1beta3
kind: Pod
metadata:
  name: puppet
  labels:
    name: puppet
spec:
  containers:
    - name: puppetmaster
      image: docker-reg.cern.ch:5000/puppetmaster:latest
      env:
        - name: LANG
          value: en_US.UTF-8
      ports:
        - containerPort: 8140
      volumeMounts:
        - name: puppet
          mountPath: /etc/puppet
        - name: factercfg
          mountPath: /etc/facter
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
        - name: puppetmodules
          mountPath: /usr/share/puppet/modules
    - name: puppetdb
      image: docker-reg.cern.ch:5000/puppetdb
      ports:
        - containerPort: 8080
        - containerPort: 8081
      volumeMounts:
        - name: puppet
          mountPath: /etc/puppet
        - name: puppetssl
          mountPath: /var/lib/puppet/ssl
    - name: teigi
      image: docker-reg.cern.ch:5000/teigi
      ports:
        - containerPort: 8082
      volumeMounts:
        - name: puppetssl
          mountPath: /ssl
        - name: teigifiles
          mountPath: /opt/teigi
  volumes:
    - name: puppet
      hostPath:
        path: /opt/puppet
    - name: factercfg
      hostPath:
        path: /opt/facter
    - name: puppetmodules
      hostPath:
        path: /opt/puppet-modules
    - name: puppetssl
      hostPath:
        path: /opt/puppetssl
    - name: teigifiles
      hostPath:
        path: /opt/teigi
