apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: puppet
  labels:
    name: puppet
spec:
  replicas: 1
  selector:
    name: puppet
  template:
    metadata:
      name: puppet
      labels:
        name: puppet
    spec:
      containers:
        - name: puppetmaster
          image: rochaporto/puppetmaster:latest
          ports:
            - containerPort: 8140
          volumeMounts:
            - name: puppetmodules
              mountPath: /etc/puppet/modules
            - name: puppetssl
              mountPath: /etc/puppet/ssl
        - name: puppetdb
          image: rochaporto/puppetdb
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: puppetssl
              mountPath: /etc/puppet/ssl
          env:
            - name: TERM
              value: xterm
          command:
            - "sh"
            - "-c"
            - "top -b"
      volumes:
        - name: puppetssl
          emptyDir: {}
        - name: puppetmodules
          hostPath:
            path: /tmp/puppet
