apiVersion: v1
kind: Pod
metadata:
  name: puppet
  labels:
    name: puppet
spec:
  containers:
    - name: puppetmaster
      image: gitlab-registry.cern.ch/cloud/puppetmaster:1
      env:
        - name: LANG
          value: en_US.UTF-8
      ports:
        - containerPort: 8140
      volumeMounts:
        - name: puppet
          mountPath: /etc/puppetlabs/puppet
        - name: factercfg
          mountPath: /etc/facter
        - name: puppetssl
          mountPath: /opt/puppetlabs/server/data/puppetserver/ssl
        - name: puppetmodules
          mountPath: /opt/puppetlabs/code
    - name: puppetdb
      image: gitlab-registry.cern.ch/cloud/puppetdb:1
      ports:
        - containerPort: 8080
        - containerPort: 8081
      volumeMounts:
        - name: puppet
          mountPath: /etc/puppetlabs/puppet
        - name: puppetssl
          mountPath: /etc/puppetlabs/puppet/ssl
    - name: teigi
      image: gitlab-registry.cern.ch/cloud/teigi
      ports:
        - containerPort: 8082
      volumeMounts:
        - name: puppetssl
          mountPath: /ssl
        - name: teigifiles
          mountPath: /opt/teigi
        - name: teigidb
          mountPath: /data
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: puppetdb
        - name: POSTGRES_DB
          value: puppetdb
        - name: POSTGRES_DB
          value: puppetdb
  volumes:
    - name: puppet
      hostPath:
        path: /opt/cloud-dev/puppet
    - name: factercfg
      hostPath:
        path: /opt/cloud-dev/facter
    - name: puppetmodules
      hostPath:
        path: /opt/puppet-modules
    - name: puppetssl
      hostPath:
        path: /opt/cloud-dev/puppetssl
    - name: teigifiles
      hostPath:
        path: /opt/cloud-dev/teigi/certs
    - name: teigidb
      hostPath:
        path: /opt/cloud-dev/teigi/data
