apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: puppet
  name: puppet
spec:
  ports:
  - name: puppet-master
    port: 8140
    protocol: TCP
  - name: puppetdb
    port: 8080
    protocol: TCP
  - name: puppetdb-ssl
    port: 8081
    protocol: TCP
  - name: teigi
    port: 8082
    protocol: TCP
  - name: landb
    port: 8083
    protocol: TCP
  - name: landbssl
    port: 8443
    protocol: TCP
  - name: landb-dhcp1
    port: 67
    protocol: UDP
  - name: landb-dhcp2
    port: 68
    protocol: UDP
  selector:
    name: puppet
