apiVersion: v1beta3
kind: Service
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    name: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kube-dns
  portalIP: 10.0.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
