apiVersion: v1beta3
kind: Pod
metadata:
  name: wigner
  labels:
    name: wigner
spec:
  hostNetwork: true
  containers:
    - name: cephall
      image: docker.cern.ch/cloud-infrastructure/cephdemo
      env:
        - name: CLUSTER
          value: wigner
        - name: MON_NAME
          value: a
        - name: MON_IP
          value: 172.17.0.1:9789
        - name: CEPH_NETWORK
          value: 172.17.0.1/24
      ports:
        - containerPort: 6800
      volumeMounts:
        - name: cephcfg
          mountPath: /etc/ceph
  volumes:
    - name: cephcfg
      hostPath:
        path: /opt/cloud-dev/ceph
