apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: www
  labels:
    name: www
spec:
  replicas: 1
  selector:
    name: www
  template:
    metadata:
      name: www
      labels:
        name: www
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: testdir
              mountPath: /testdir
        - name: db
          resources:
            limits:
              cpu: 1
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '123456'
          volumeMounts:
            - name: testdir
              mountPath: /testdir
      volumes:
        - name: testdir
          emptyDir: {}
